### ISSUE TITLE
Karma tests left orphaned on multiple saves

### ISSUE THREAD

**Issue by brandoncazander** [skoczen/polytester#16]
I've noticed an oddity when including a karma auto-reload test that uses karma-chrome-launcher. When the auto-reload runs twice (i.e., when saving two python files rapidly), one chrome window is left orphaned. My testing seems to show that if the change is very quick, this doesn't occur. However, if the second save comes before the tests finish completing, the issue can be replicated.

Here is my test.yml:

``` yml
api:
    command: env/bin/nosetests
    watch_glob: "**/*.py"
    watch_dir: pendulum
js:
    command: karma start karma.conf.js --single-run
    watch_glob: "**/*.js"
    watch_dir: static
```

Here is the output of strace:

``` bash
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0}
)     = ? ERESTARTNOHAND (To be restarted if no handler)
select(0, NULL, NULL, NULL, {0, 970075}Change detected in 'test_index.py' in the api suite. Reloading...

) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=13864, si_uid=1000, si_status=SIGTERM, si_utime=0, si_stime=0} ---
Running tests...
select(0, NULL, NULL, NULL, {0, 967938}
) = ? ERESTARTNOHAND (To be restarted if no handler)
select(0, NULL, NULL, NULL, {0, 453176}Change detected in 'common.py' in the api suite. Reloading...

Running tests...
) = 0 (Timeout)
futex(0xa6b060, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0}  ✘ api: 1 of 1 tests failed.

    F
    ======================================================================
    FAIL: test_something (test_index.IndexTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/brandon/Projects/github.com/typescript-test/pendulum/tests/test_index.py", line 6, in test_something
        assert False
    AssertionError

    ----------------------------------------------------------------------
    Ran 1 test in 0.009s

    FAILED (failures=1)

  ✔ js: tests passed.
ERROR: ✘ Tests failed.

)     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
```

**Comment by brandoncazander** [comment]
Upon further testing, this does not appear to occur when using the `--verbose` flag, although that raises an exception on my system:

```
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brandon/Projects/github.com/polytester/polytester/runner.py", line 355, in run_tests
    puts(line.decode("utf-8"))
  File "/home/brandon/Projects/github.com/typescript-test/env/lib/python2.7/site-packages/clint/textui/core.py", line 58, in puts
    s = map(str, s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 14: ordinal not in range(128)
```
