### ISSUE TITLE
Traceback when killing tests with CTRL + C

### ISSUE THREAD

**Issue by joshfriend** [skoczen/polytester#2]
Looks like the `time.sleep()` call should have a try/except for `KeyboardInterrupt` like the other calls:

```
Running tests...
^CTraceback (most recent call last):
  File "/Users/josh/.pyenv/versions/2.7.9/bin/polytester", line 9, in <module>
    load_entry_point('polytester==1.0.1', 'console_scripts', 'polytester')()
  File "/Users/josh/.pyenv/versions/2.7.9/lib/python2.7/site-packages/polytester/main.py", line 27, in main
    runner.run()
  File "/Users/josh/.pyenv/versions/2.7.9/lib/python2.7/site-packages/polytester/runner.py", line 345, in run
    time.sleep(0.5)
KeyboardInterrupt
```

**Comment by skoczen** [comment]
Turned out to be that I forgot to set `.daemon = True` ( Don't need it in python 3.x).  Thanks for the debugging info!

**Comment by skoczen** [comment]
[1.0.2](https://github.com/skoczen/polytester#releases) is out, and should fix this - please reopen if you still see anything odd!

**Comment by joshfriend** [comment]
Still a bit weird. See 865955.
